#ifndef __SCRYFALLCACHE_BASE_H__
#define	__SCRYFALLCACHE_BASE_H__

#include <stddef.h>
#include <stdint.h>

#ifdef  __cplusplus
extern "C"
{
#endif

#define SFC_MAX_SET									5
#define SFC_MAX_COLLECTOR_NUMBER_STRING				16

#define SFC_RESULT_OK								0
#define SFC_RESULT_HTTP_PROTOCOL_ERROR				-1
#define SFC_RESULT_JSON_PARSE_ERROR					-4
#define SFC_RESULT_HTTP_GET_FAILED					-2
#define SFC_RESULT_JSON_RESPONSE_ERROR				-5
#define SFC_RESULT_JSON_NAME_TOO_LONG				-6
#define SFC_RESULT_JSON_SET_TOO_LONG				-7
#define SFC_RESULT_JSON_NO_COLLECTOR_NUMBER			-8
#define SFC_RESULT_JSON_NO_SET						-9
#define SFC_RESULT_JSON_COLLECTOR_NUMBER_TOO_LARGE	-10
#define SFC_RESULT_NOT_FOUND						-11
#define SFC_RESULT_REQUEST_NEEDS_VERSION			-13
#define SFC_RESULT_FAILED_TO_OPEN_FILE_FOR_OUTPUT	-14
#define SFC_RESULT_BUFFER_TOO_SMALL					-15
#define SFC_RESULT_FAILED_TO_WRITE_TO_FILE			-16
#define SFC_RESULT_STRING_TOO_LONG					-17
#define SFC_RESULT_NOT_ENOUGH_DATA					-18
#define SFC_RESULT_VAR_SIZE_UINT32_TOO_BIG			-19
#define SFC_RESULT_MISSING_NULL_TERMINATION			-20
#define SFC_RESULT_RENAME_FAILED					-21
#define SFC_RESULT_FAILED_TO_OPEN_FILE_FOR_INPUT	-22
#define SFC_RESULT_SERIALIZED_CARD_TOO_LARGE		-23
#define SFC_RESULT_FAILED_TO_READ_FROM_FILE			-24
#define SFC_RESULT_UINT16_TOO_BIG					-25
#define SFC_RESULT_MISSING_COLLECTORS_NUMBER		-26
#define SFC_RESULT_ALREADY_EXISTS					-27
#define SFC_RESULT_INTERNAL_ERROR					-28
#define SFC_RESULT_FILE_READ_ERROR					-29
#define SFC_RESULT_FILE_WRITE_ERROR					-30
#define SFC_RESULT_FILE_RENAME_ERROR				-31
#define SFC_RESULT_FILE_OPEN_ERROR					-32
#define SFC_RESULT_OUT_OF_BOUNDS					-33
#define SFC_RESULT_TIMED_OUT						-34

typedef int sfc_result;

#define SFC_TRUE									1
#define SFC_FALSE									0

typedef int sfc_bool;

#define SFC_UNUSED(_x)								((void)_x)

#ifdef  __cplusplus
}
#endif

#endif /* __SCRYFALLCACHE_BASE_H__ */
